---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that:
          - true
        fail_msg: Please add role-specific tests to verify.yml
